export const projects = [
  {
    id: 2,
    title: 'NC News',
    desc: '"Northcoders News" is a full-stack project created on the Northcoders course. The front end is a single page responsive web app built in React, while the back end is an Node.js/Express server fed by a PostgreSQL database. The app functions as a news aggregation and commentary board, with additional features available to a logged in user.',
    descTest: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto dolor eum alias asperiores, earum labore pariatur officia sunt expedita cumque sed quis quasi eligendi. Illo consectetur neque, ad, reiciendis iste voluptate quae, itaque debitis nobis ex ratione consequatur. Nobis velit consequatur culpa maiores dolore error sint nostrum quidem hic alias.',
    imgSml: 'ncnews-sml.png',
    imgMed: 'ncnews-med.png',
    techList: ['faReact', 'faCss3', 'faNodeJs'],
    techListStr: 'React | Node.js | PostgreSQL',
    githubUrl: 'https://github.com',
    hostedUrl: 'https://google.com',
  },
  {
    id: 4,
    title: 'Gaffr',
    descTest: 'A team project, "Gaffr" is a mobile application designed to make property hunting more approachable. Inspired by dating apps, tenants swipe on properties uploaded by landlords to find the home of their dreams! The app was written in TypeScript, using React Native for the mobile application and Google Firebase and Firestore for authentication and data storage respectively.',
    imgMed: 'gaffr-lrg.png',
    techList: ['faReact', 'faCss3'],
    techListStr: 'React Native | TypeScript | Firebase',
    githubUrl: 'https://github.com',
    hostedUrl: '',
    youtubeUrl: 'https://youtube.com',
  },
  {
    id: 1,
    title: 'Lemonade Tycoon',
    desc: '"Lemonade Tycoon Simulator Extreme 2019 Game of the Year Edition", or "Lemonade Tycoon" is a resource management game created as a hobby during my time on the Northcoders course. The player purchases lemons, squeezes them into lemonade and sells them for profit, gradually unlocking upgrades to boost productivity. Made in React and hosted on Heroku.',
    descTest: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto dolor eum alias asperiores, earum labore pariatur officia sunt expedita cumque sed quis quasi eligendi. Illo consectetur neque, ad, reiciendis iste voluptate quae, itaque debitis nobis ex ratione consequatur. Nobis velit consequatur culpa maiores dolore error sint nostrum quidem hic alias.',
    imgSml: 'lemonade-sml.png',
    imgMed: 'lemonade-lrg.png',
    techList: ['faReact', 'faCss3'],
    techListStr: 'React | CSS',
    githubUrl: 'https://github.com',
    hostedUrl: 'https://google.com',
  },
  {
    id: 3,
    title: 'GraphQL Film App',
    descTest: 'A full stack project, created to gain experience with GraphQL, that allows users to view related information about films and directors, as well as add their own films. The app features an Express server back end, utilising GraphQL, and a MongoDB Atlas instance for a database. It also has a simple front end made in React, using Apollo to interface with the API.',
    imgMed: 'graphql-test-lrg.png',
    techList: ['faReact', 'faGraphQl', 'faNodeJs'],
    techListStr: 'React | GraphQL | Node.js',
    githubUrl: 'https://github.com',
    hostedUrl: 'https://google.com',
  },
];
